version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger
    ports:
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
    environment:
      - JAEGER_LOG_LEVEL=debug
    command:
      - "--set"
      - "receivers.otlp.protocols.http.endpoint=0.0.0.0:4318"
      - "--set"
      - "receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317"
    restart: unless-stopped
