logger:
  enable: {{ get_env(name="LOGGER_ENABLE", default="true") }}
  pretty_backtrace: true
  level: {{ get_env(name="LOGGER_LEVEL", default="info") }}
  format: compact
server:
  port: {{ get_env(name="SERVER_PORT", default="5150") }}
  host: {{ get_env(name="SERVER_HOST", default="http://localhost") }}
  middlewares:
    static:
      enable: {{ get_env(name="MIDDLEWARE_STATIC_ENABLED", default="false") }}
      must_exist: {{ get_env(name="MIDDLEWARE_STATIC_MUST_EXIST", default="false") }}
      precompressed: false
      folder:
        uri: {{ get_env(name="MIDDLEWARE_STATIC_FOLDER_URI", default="/") }}
        path: {{ get_env(name="MIDDLEWARE_STATIC_FOLDER_PATH", default="frontend/dist") }}
      fallback: {{ get_env(name="MIDDLEWARE_STATIC_FALLBACK", default="frontend/dist/index.html") }}
workers:
  mode: BackgroundAsync
mailer:
  smtp:
    enable: {{ get_env(name="MAILER_ENABLE", default="false") }}
    host: {{ get_env(name="MAILER_HOST", default="localhost") }}
    port: {{ get_env(name="MAILER_PORT", default="1025") }}
    secure: {{ get_env(name="MAILER_SECURE", default="false") }}
database:
  uri: {{ get_env(name="DATABASE_URL", default="postgres://postgres:postgres@localhost:5432/postgres") }}
  enable_logging: false
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT", default="500") }}
  idle_timeout: 500
  min_connections: 1
  max_connections: 1
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false
queue:
  kind: {{ get_env(name="QUEUE_KIND", default="Redis") }}
  uri: {{ get_env(name="QUEUE_URL", default="redis://127.0.0.1") }}
  dangerously_flush: false
auth:
  jwt:
    secret: {{ get_env(name="JWT_SECRET", default="secret") }}
    expiration: {{ get_env(name="JWT_EXPIRATION", default="604800") }}
