[workspace]
members = ["protypo", "protypo-cli"]
exclude = ["output/**", "generators/**"]
resolver = "2"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
strip = true
debug = false
panic = "abort"
