to: "{{ values.outputFolder }}/dockerfile.fullstack.alpine"
message: "Created dockerfile.fullstack.alpine"
---
FROM rust:alpine as builder

WORKDIR /app/src
RUN USER=root

RUN apk add --no-cache pkgconfig build-base musl-dev libressl-dev
COPY ./ ./
RUN cargo build --release

FROM node:lts-slim as node-builder

WORKDIR /usr/src

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

FROM alpine:latest
WORKDIR /app
RUN apk update && apk add openssl ca-certificates

COPY --from=node-builder /usr/src/dist /app/dist
COPY --from=builder /app/src/target/release/{{ values.application.name }} /app/{{ values.application.name }}
COPY --from=builder /app/src/config /app/config

ENTRYPOINT ["/app/{{ values.application.name }}"]
CMD ["start"]