name: Release Rust Crate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release-cli:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          manifest_path: protypo/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}